# Generated by Django 3.2.8 on 2021-10-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_delete_pokemonabilities'),
        ('abilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='pokemon',
            field=models.ManyToManyField(to='pokemon.Pokemon'),
        ),
    ]
