# Generated by Django 3.2.8 on 2021-10-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0001_initial'),
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonabilities',
            name='ability',
        ),
        migrations.AddField(
            model_name='pokemonabilities',
            name='ability',
            field=models.ManyToManyField(to='abilities.Ability'),
        ),
        migrations.RemoveField(
            model_name='pokemonabilities',
            name='pokemon',
        ),
        migrations.AddField(
            model_name='pokemonabilities',
            name='pokemon',
            field=models.ManyToManyField(to='pokemon.Pokemon'),
        ),
    ]
