# Generated by Django 3.2.8 on 2021-10-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_auto_20211027_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonabilities',
            name='pokemon',
        ),
        migrations.AddField(
            model_name='pokemonabilities',
            name='pokemon',
            field=models.ManyToManyField(to='pokemon.Pokemon'),
        ),
    ]
