# Generated by Django 3.2.8 on 2021-10-27 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_auto_20211027_1114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PokemonAbilities',
        ),
    ]
