# Generated by Django 3.2.8 on 2021-10-27 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_delete_pokemonabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonstats',
            name='base_experience',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
