# Generated by Django 3.2.8 on 2021-10-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0007_remove_pokemonstats_base_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonstats',
            name='base_experience',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
